services:
  fastapi:
    build: .
    ports:
      - 8001:8000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL="postgresql://myname:mypass@db:5432/database"
      - ENCRIPTION_KEY='1UNdvi1NKUpdqFobrklCNDZTlrNARUP9clYAA2nZz5g='
      - POSTGRES_USER=myname
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=database
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: myname
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data: